# Generated by Django 6.0.5 on 2026-05-19 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0019_alter_customservice_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVESource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("redhat", "Red Hat Security Data"),
                            ("nvd", "NVD / NIST"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("api_url", models.URLField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CVEDashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("cve_table", "CVE Table"),
                            ("severity_chart", "Severity Distribution Chart"),
                            ("timeline_chart", "Timeline Chart"),
                            ("unacked_count", "Unacknowledged Count"),
                            ("top_packages", "Top Affected Packages"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                ("config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cve_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "position"],
            },
        ),
        migrations.CreateModel(
            name="CVE",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cve_id", models.CharField(db_index=True, max_length=30)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("important", "Important"),
                            ("moderate", "Moderate"),
                            ("low", "Low"),
                            ("none", "None"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "cvss3_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("cvss3_vector", models.CharField(blank=True, max_length=200)),
                ("public_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("affected_packages", models.JSONField(default=list)),
                ("advisories", models.JSONField(default=list)),
                ("cwe", models.CharField(blank=True, max_length=100)),
                ("bugzilla", models.CharField(blank=True, max_length=50)),
                ("bugzilla_description", models.TextField(blank=True)),
                ("resource_url", models.URLField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledgement_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_cves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "affected_agents",
                    models.ManyToManyField(
                        blank=True, related_name="cves", to="agents.agent"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cves",
                        to="cves.cvesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-public_date", "-cvss3_score"],
                "indexes": [
                    models.Index(
                        fields=["severity"], name="cves_cve_severit_57c4b6_idx"
                    ),
                    models.Index(
                        fields=["acknowledged"], name="cves_cve_acknowl_c3479c_idx"
                    ),
                    models.Index(
                        fields=["public_date"], name="cves_cve_public__bd1ccc_idx"
                    ),
                ],
                "unique_together": {("cve_id", "source")},
            },
        ),
    ]
