# Generated by Django 6.0.5 on 2026-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cve",
            name="affected_releases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cve",
            name="cvss2_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="cve",
            name="cvss2_vector",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cve",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cve",
            name="details_fetched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cve",
            name="mitigation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cve",
            name="package_state",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cve",
            name="references",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cve",
            name="statement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cve",
            name="upstream_fix",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cvedashboardwidget",
            name="size",
            field=models.CharField(
                choices=[
                    ("full", "Full Width"),
                    ("half", "Half Width"),
                    ("quarter", "Quarter Width"),
                ],
                default="half",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cvesource",
            name="default_days_back",
            field=models.PositiveIntegerField(
                default=365,
                help_text="Fetch CVEs published in the last N days (0 = all time)",
            ),
        ),
    ]
