# Generated by Django 5.2.7 on 2025-10-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="agent_api_key",
            field=models.CharField(
                blank=True, help_text="API key for agent authentication", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="agent_port",
            field=models.IntegerField(
                default=8444, help_text="Port where agent listens for connections"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("agent_to_server", "Agent connects to Server"),
                    ("server_to_agent", "Server connects to Agent"),
                    ("ssh", "SSH Connection"),
                ],
                default="agent_to_server",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="ssh_key_path",
            field=models.CharField(
                blank=True, help_text="Path to SSH private key", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="ssh_password",
            field=models.CharField(
                blank=True,
                help_text="SSH password (use key-based auth when possible)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="ssh_username",
            field=models.CharField(
                blank=True, help_text="Username for SSH connections", max_length=100
            ),
        ),
    ]
