# Generated by Django 5.2.8 on 2025-11-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_auto_20251019_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="last_sync",
            field=models.DateTimeField(
                blank=True, help_text="Last time firewall config was synced", null=True
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="sync_interval_seconds",
            field=models.IntegerField(
                default=60,
                help_text="Interval in seconds for automatic firewall configuration sync (0 to disable)",
            ),
        ),
    ]
