# Generated by Django 5.2.8 on 2025-11-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agent_last_sync_agent_sync_interval_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="available_services",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of available firewalld services on this agent",
            ),
        ),
    ]
